# Generated by Django 3.1 on 2021-06-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210617_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='priority',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='title',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='Status',
        ),
    ]
